import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./_components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full max-w-[100vw] min-h-[100vh] bg-gray-200 relative pb-10">
        <Navbar />
        <div className="mt-[75px] flex justify-center">
          <div className="max-w-[1170px] w-full px-[10px] sm:px-[30px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
